[[vote_sources]]
url = "https://www.leipzig.de/buergerservice-und-verwaltung/wahlen-in-leipzig/stadtratswahlen/stadtratswahl-2024"
name = "Leipzig_Stadtratswahl_2024"

[vote_sources.party_map]
E1 = "Die Linke"
E2 = "Grüne"
E3 = "CDU"
E4 = "AfD"
E5 = "SPD"
E6 = "FDP"
E7 = "Die Partei"
E11 = "BSW"

[[vote_sources]]
url = "https://www.leipzig.de/buergerservice-und-verwaltung/wahlen-in-leipzig/europawahlen/europawahl-2024"
name = "Leipzig_Europawahl_2024"

[vote_sources.party_map]
D1 = "AfD"
D2 = "CDU"
D3 = "Die Linke"
D4 = "Grüne"
D5 = "SPD"
D6 = "FDP"
D8 =  "Die Partei"
D28 = "BSW"

[[vote_sources]]
url = "https://wahlergebnis.leipzig.de/4/bt2025/14713000/daten/opendata/Open-Data-14713000-Bundestagswahl-Ortsteil.csv?ts=1740994679432"
name = "Bundestagswahl_Zweitstimme_2025"

[vote_sources.party_map]
D1 = "AfD"
D2 = "SPD"
D3 = "CDU"
D4 = "FDP"
D5 = "Die Linke"
D6 = "Die Grünen"
D9 =  "Die Partei"
D15 = "BSW"